export const products = [
  {
    id: 1,
    title: "Mac Special Pizza",
    price:183,
    img: "https://static.uengage.in/uploads/5/image-827162-1595939023.jpeg",
    description: "Cheesy Mac, Onions, Olives, Sweet Corns, Mushroom.(7-inch)",
    quantity: 0,
    Rating: "4.0",
  },
  {
    id: 2,
    title: "Veg.hawaiian Pizza",
    price:171,
    img: "https://static.uengage.in/uploads/5/image-1560414882.jpeg",
    description: "Pineapple, Paneer, Sweet Corns with Extra Cheese.(7-inch)",
    quantity: 0,
    Rating: "3.8",
  },
  {
    id: 3,
    title: "Panner Pizza",
    price:180,
    img: "https://foodoncall.co.in/wp-content/uploads/2017/10/chatpata-paneer-pizza.jpg",
    description: "Onion, Capsicum, Paneer, Sweet Corn & Olives.(7-inch)",
    quantity: 0,
    Rating: "4.2",
  },
  {
    id: 4,
    title: "Hot Passion Pizza",
    price:191,
    img: "https://static.uengage.in/uploads/5/image-1578569568.jpeg",
    description: "Jalapenos, Mushrooms, Red Paprika, Fresh Tomato.(7-inch)",
    quantity: 0,
    Rating: "3.9",
  },
  {
    id: 5,
    title: "Farm Villa Pizza",
    price:185,
    img: "https://static.uengage.in/uploads/5/image-827281-1595939023.jpeg",
    description: "Capsicum, Fresh Tomatoes, Paneer, Red Paprika.(7-inch)",
    quantity: 0,
    Rating: "3.7",
  },
  {
    id: 6,
    title: "Vegetable Pizza",
    price:160,
    img: "https://static.uengage.in/uploads/5/image-1578569630.jpeg",
    description: "Onion, Tomatoes, Capsicum.(7-inch)",
    quantity: 0,
    Rating: "3.5",
  },
  {
    id: 7,
    title: "Red Sauce Pasta",
    price:160,
    img: "https://www.chelseasmessyapron.com/wp-content/uploads/2014/02/Red-and-White-Pasta-3.jpg",
    description: "Red Sauce with Onion, Capsicum, Mushroom, Olives & Cheese.",
    quantity: 0,
    Rating: "4.5",
  },
  {
    id: 8,
    title: "White Cheese Sauce Pasta",
    price:160,
    img: "https://i.ytimg.com/vi/QK3EHf6xH-k/maxresdefault.jpg",
    description:
      "White Sauce, Onion, Capsicum, Sweet Corn, Mushrooms, Olives & Cheese.",
    quantity: 0,
    Rating: "4.0",
  },
  {
    id: 9,
    title: "Cheese Lasagane",
    price:190,
    img: "https://www.lovefromtheoven.com/wp-content/uploads/2020/01/lasagna-3.webp",
    description:
      "Mozzarella cheese, Parmesan cheese, Lasagna noodles and fresh oregano.",
    quantity: 0,
    Rating: "4.6",
  },
  {
    id: 10,
    title: "Chilli Panner",
    price:185,
    img: "https://i2.wp.com/www.yummytummyaarthi.com/wp-content/uploads/2014/09/1-27.jpg?ssl=1",
    description: "Panner and Capsicum cooked in Chilly Schezwan Sauce. ",
    quantity: 0,
    Rating: "3.8",
  },
  {
    id: 11,
    title: "Dragon Potato",
    price:185,
    img: "https://efoodcorp.files.wordpress.com/2018/12/13-28.jpg",
    description:
      "Potato, Chopped Onion & Garlic cooked in Red & Green Chilly Sauce.",
    quantity: 0,
    Rating: "3.3",
  },
  {
    id: 12,
    title: "Fried Rice",
    price:150,
    img: "https://i2.wp.com/chefsavvy.com/wp-content/uploads/the-best-fried-rice.jpg?w=665&ssl=1",
    description:
      "Fresh Veggies and Rice cooked in Sesame Oil, Soya Sauce & Oyster Sauce.",
    quantity: 0,
    Rating: "4.2",
  },
  {
    id: 13,
    title: "Manchurian Gravy",
    price:170,
    img: "https://www.cookforindia.com/wp-content/uploads/2016/06/dry-manchurian.jpg-1.JPG-4.jpg",
    description:
      "Chopped Veggies mixed in Cornflour and garlic paste cooked in Oil & Red Chilly Sauce.",
    quantity: 0,
    Rating: "4.7",
  },
  {
    id: 14,
    title: "Manchurian Dry",
    price:155,
    img: "https://i2.wp.com/www.bharatzkitchen.com/wp-content/uploads/2017/06/veg-manchurian-thumb1.jpg?zoom=1.25&resize=575%2C262&ssl=1",
    description:
      "Chopped Veggies mixed in Cornflour and garlic paste that is cooked with Red Chilly Sauce.",
    quantity: 0,
    Rating: "4.2",
  },
  {
    id: 15,
    title: "Dosa",
    price:90,
    img: "https://assets.cntraveller.in/photos/60ba1de12267328f9d2456f0/16:9/w_1024%2Cc_limit/dosa-recipes-1366x768.jpg",
    description:
      "A regular dosa with potato filling that is cooked with green chillies and curry leaves.",
    quantity: 0,
    Rating: "3.4",
  },
  {
    id: 16,
    title: "Fried Idli",
    price:90,
    img: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/05/idly-fry.jpg",
    description: "Idli fried in Peanut and served with Red Chilly & Sambhar",
    quantity: 0,
    Rating: "3.7",
  },
  {
    id: 17,
    title: "Idli Sambhar",
    price:80,
    img: "https://media.istockphoto.com/photos/idly-sambar-or-idli-with-sambhar-and-green-red-chutney-popular-south-picture-id1024549286?k=6&m=1024549286&s=612x612&w=0&h=ru9RBzXUNeD_a38mZbvH2J29seGc--fZcWotFr0gJVQ=",
    description: "Idli served with Hot Sambhar and Coconut chutney.",
    quantity: 0,
    Rating: "3.6",
  },
  {
    id: 18,
    title: "Mysore Masala Dosa",
    price:125,
    img: "http://www.volunteerworkindia.org/wp-content/uploads/2014/05/Dosa-Image2-Copy.jpg",
    description:
      "Crisp on the outside dosa is smeared with a fiery thick red chilli paste and stuffed with a potato-onion",
    quantity: 0,
    Rating: "4.0",
  },
  {
    id: 19,
    title: "Masala Dosa",
    price:110,
    img: "https://holycowvegan.net/wp-content/uploads/2014/04/masala-dosa-1.jpg",
    description:
      "A regular dosa with a spicy potato filling that is cooked with green chillies and curry leaves.",
    quantity: 0,
    Rating: "3.7",
  },
  {
    id: 20,
    title: "Rawa Dosa",
    price:105,
    img: "https://i2.wp.com/fforflavour.com/wp-content/uploads/2018/07/rava-dosa.jpg?w=855&ssl=1",
    description:
      "Thin and extremely crispy dosa prepared using rava mixed with onions and green chillies",
    quantity: 0,
    Rating: "3.2",
  },
  {
    id: 21,
    title: "Panner Tikka Dosa",
    price:135,
    img: "https://www.subbuskitchen.com/wp-content/uploads/2017/11/0-11.jpg",
    description:
      "A regular dosa with a spicy panner tikka filling that is cooked with green chillies and curry leaves.",
    quantity: 0,
    Rating: "3.8",
  },
  {
    id: 22,
    title: "Vegetable Burger",
    price:80,
    img: "https://image.shutterstock.com/image-photo/tasty-vegetarian-burger-carrot-cutlet-260nw-1311655739.jpg",
    description: "Fresh Veggies served with crisp potato patty & Mayoneese.",
    quantity: 0,
    Rating: "3.6",
  },
  {
    id: 23,
    title: "Chilly Cheese Patty Burger",
    price:120,
    img: "https://media.istockphoto.com/photos/big-burger-and-juice-picture-id1166796947?k=6&m=1166796947&s=612x612&w=0&h=H_KHEbluVYhK2JO3bw89CJzdN_odS3z5jI3L4eE62Ug=",
    description:
      "Chilly potato patty served with chilly mayoneese, veggies and cheese.",
    quantity: 0,
    Rating: "4.4",
  },
  {
    id: 24,
    title: "Panner Burger",
    price:120,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn_GvwZ7jLkxMoVwBK97n_mpyl_RRQ7iRz5g&usqp=CAU",
    description: "Crisp panner patty served with chesse and veggies",
    quantity: 0,
    Rating: "4.1",
  },
  {
    id: 25,
    title: "Cheese Sandwich",
    price:60,
    img: "https://www.recipetineats.com/wp-content/uploads/2021/04/Croque-Monsieur_0.jpg",
    description:
      "Sandwich baked to perfection filled with Margherita Chesse and Onion.",
    quantity: 0,
    Rating: "3.3",
  },
  {
    id: 26,
    title: "Vegetable Sandwich",
    price:50,
    img: "https://simply-delicious-food.com/wp-content/uploads/2020/07/Easy-salad-sandwiches-with-herb-mayo-5.jpg",
    description:
      "Sandwich grilled to perfection filled with fresh Veggie and Onion.",
    quantity: 0,
    Rating: "3.5",
  },
  {
    id: 27,
    title: "Chilly Cheese Garlic Toast",
    price:130,
    img: "https://cafedelites.com/wp-content/uploads/2017/10/Individual-Garlic-Breads-IMAGE-10.jpg",
    description:
      "Grilled bread topped with onion-garlic paste, cheese, origano and jalapeno .",
    quantity: 0,
    Rating: "4.6",
  },
  {
    id: 28,
    title: "Orange Juice",
    price:40,
    img: "https://harvestlagos.com/wp-content/uploads/2021/04/FRESH-ORANGE-JUICE-fresh-oranges.jpeg",
    description: "Fresh orange juice served with ice.",
    quantity: 0,
    Rating: "4.0",
  },
  {
    id: 29,
    title: "Pineapple Juice",
    price:40,
    img: "https://cdn.healthyrecipes101.com/wp-content/uploads/2020/11/Healthy-Pineapple-Mango-Juice-Recipe.jpg",
    description: "Fresh pineapple juice served with ice.",
    quantity: 0,
    Rating: "3.9",
  },
  {
    id: 30,
    title: "Pomegranate Juice",
    price:50,
    img: "https://cdn.cdnparenting.com/articles/2018/09/182985467-H.jpg",
    description: "Fresh Pomegranate juice served with ice.",
    quantity: 0,
    Rating: "3.6",
  },
  {
    id: 31,
    title: "Water Melon Juice",
    price:40,
    img: "https://media.istockphoto.com/photos/cold-watermelon-smoothie-picture-id483748240?k=6&m=483748240&s=612x612&w=0&h=awZFIC79E1pBNJkac-EY4HrHxiYJQJq7b12V3VeiVyc=",
    description: "Fresh water melon juice served with ice.",
    quantity: 0,
    Rating: "3.5",
  },
  {
    id: 32,
    title: "Mango Juice",
    price:40,
    img: "https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2018/04/25/Pictures/_352264d0-485a-11e8-b38d-ae9d3b5e5930.jpg",
    description: "Fresh Mango juice served with ice.",
    quantity: 0,
    Rating: "4.0",
  },
  {
    id: 33,
    title: "Oreo Shake",
    price:100,
    img: "https://t3.ftcdn.net/jpg/02/30/66/50/360_F_230665016_Tqv1eY4MZJlHUrR8J3KR5nmlQOTmxHlH.jpg",
    description:
      "Vanilla ice cream, Milk, Choclate Sauce and Oreo blended to perfection.",
    quantity: 0,
    Rating: "4.8",
  },
  {
    id: 34,
    title: "Choco Brownie Shake",
    price:140,
    img: "https://wellsmanagedcontent.azureedge.net/content/foodservice/recipe/rich-media/9c65c681-7c87-47e1-990d-d95135b78767/molten-volcano-shake.v1.jpg",
    description:
      "Vanilla ice cream, Milk, Choclate Sauce blended to perfection topped with choco lava cake",
    quantity: 0,
    Rating: "4.8",
  },
  {
    id: 35,
    title: "Blue Lagoon Mocktail",
    price:80,
    img: "https://media.istockphoto.com/photos/blue-cocktails-decorated-with-lemon-picture-id953173040?k=6&m=953173040&s=612x612&w=0&h=64vT8FIbD8inHbVrpWTqkzp4-qVqCWIOm6QYoOVi1Ug=",
    description:"Blue Curaçao syrup mixed with Lemon juice and Sprite served with Ice",
    quantity: 0,
    Rating: "4.2",
  },
  {
    id: 36,
    title: "Dry Fruit Masti Faluda",
    price:110,
    img: "https://i.pinimg.com/originals/82/3b/1d/823b1d2113811ba150e398cbaddb266c.jpg",
    description:"Alphonso Mango crused in Milk and Mango Ice Cream topped with Chopped Nuts",
    quantity: 0,
    Rating: "4.4",
  },
];
